//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMNI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".pdf")]
        public string DefaultPrintExtension {
            get {
                return ((string)(this["DefaultPrintExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\manage2\\server\\OMNI\\Application Data\\QIR Photos\\")]
        public string QIRPhotoDirectory {
            get {
                return ((string)(this["QIRPhotoDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\manage2\\server\\Engineering\\Product\\Prints\\Controlled Production Prints\\")]
        public string PrintLocation {
            get {
                return ((string)(this["PrintLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("172.16.0.10")]
        public string ManageHostName {
            get {
                return ((string)(this["ManageHostName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:/roi/WCCO.MAIN")]
        public string WCCOManageAccount {
            get {
                return ((string)(this["WCCOManageAccount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\manage2\\server\\Document Center\\Production\\")]
        public string WCCODocumentLocation {
            get {
                return ((string)(this["WCCODocumentLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtp.office365.com")]
        public string SmtpDefaultClient {
            get {
                return ((string)(this["SmtpDefaultClient"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("itsupport@wccobelt.com")]
        public string omniEmailAddress {
            get {
                return ((string)(this["omniEmailAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\manage2\\server\\OMNI\\Application Data\\temp\\")]
        public string omnitemp {
            get {
                return ((string)(this["omnitemp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1015")]
        public int CSISupplierNumber {
            get {
                return ((int)(this["CSISupplierNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\manage2\\server\\Document Center\\Production\\FORM5008 - Quality Incident Report.pd" +
            "f")]
        public string QIRDocument {
            get {
                return ((string)(this["QIRDocument"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wccobelt.com")]
        public string EmailDomain {
            get {
                return ((string)(this["EmailDomain"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vbty6^743[\\<tyF4")]
        public string EmailPassword {
            get {
                return ((string)(this["EmailPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\manage2\\server\\OMNI\\Pending Update\\ClickOnce\\OMNI.application")]
        public string omniAppLocation {
            get {
                return ((string)(this["omniAppLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\manage2\\server\\OMNI\\Application Data\\CMMS Documents\\")]
        public string CMMSDocumentLocation {
            get {
                return ((string)(this["CMMSDocumentLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\manage2\\server\\Document Center\\Production\\FORM5006E - Maintenance Request.pdf")]
        public string CMMSWorkOrderDocument {
            get {
                return ((string)(this["CMMSWorkOrderDocument"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\manage2\\server\\QIR\\Photos")]
        public string QIRArchivePhotoDirectory {
            get {
                return ((string)(this["QIRArchivePhotoDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\manage2\\server\\QIR\\Archived QIRs")]
        public string QIRArchiveDocumentDirectory {
            get {
                return ((string)(this["QIRArchiveDocumentDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\manage2\\server\\Quality\\Inspection\\Extruder Quality Inspection\\Extruder Quality " +
            "Inspection.xlsm")]
        public string ExtruderExcelFilePath {
            get {
                return ((string)(this["ExtruderExcelFilePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\manage2\\server\\Document Center\\Production\\FRM-5761 - Employee Performance Revie" +
            "w.pdf")]
        public string ERDFilePath {
            get {
                return ((string)(this["ERDFilePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\manage2\\server\\OMNI\\Application Data\\HDT Documents\\")]
        public string HDTDocumentLocation {
            get {
                return ((string)(this["HDTDocumentLocation"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:/roi/CSI.MAIN")]
        public string CSIManageAccount {
            get {
                return ((string)(this["CSIManageAccount"]));
            }
            set {
                this["CSIManageAccount"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\manage2\\server\\Document Center\\Photo Library\\Employees")]
        public string UsersPhotoDirectory {
            get {
                return ((string)(this["UsersPhotoDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=SQL-WCCO;User ID=omni;Password=Public2017@WORK!;Connection Timeout=5;Multi" +
            "pleActiveResultSets=True")]
        public string SqlConnectionString {
            get {
                return ((string)(this["SqlConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\CSI-PRIME\\FileStorage\\Published Documents\\")]
        public string CSIDocumentLocation {
            get {
                return ((string)(this["CSIDocumentLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\manage2\\server\\Document Center\\Production\\FORM5125 - Travel Card.pdf")]
        public string TravelCardDocument {
            get {
                return ((string)(this["TravelCardDocument"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("omniquery")]
        public string ManageAccount {
            get {
                return ((string)(this["ManageAccount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\manage2\\server\\Document Center\\Production\\FORM5127 - Reference Travel Card.pdf")]
        public string ReferenceCardDocument {
            get {
                return ((string)(this["ReferenceCardDocument"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\ERP-WCCO\\ERP\\ROI\\WCCO.MAIN\\BTI.TRANSACTIONS\\")]
        public string MoveFileLocation {
            get {
                return ((string)(this["MoveFileLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("technology#1")]
        public string PdfDefaultPassword {
            get {
                return ((string)(this["PdfDefaultPassword"]));
            }
        }
    }
}
